# Generated by Django 3.1.2 on 2020-11-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_book_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_no', models.CharField(max_length=50, unique=True)),
                ('book_name', models.CharField(max_length=50)),
                ('book_author', models.CharField(max_length=50)),
                ('book_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='add_staff_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=30)),
                ('staff_mob_no', models.CharField(max_length=25, unique=True)),
                ('staff_email', models.CharField(max_length=50, unique=True)),
                ('staff_pass', models.CharField(max_length=50)),
                ('staff_img', models.ImageField(default='', upload_to='static/ImgStaff/')),
            ],
        ),
    ]
