# Generated by Django 3.1.2 on 2020-11-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_section_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=70)),
                ('branch_name', models.CharField(max_length=50)),
            ],
        ),
    ]
