# Generated by Django 3.1.2 on 2020-12-03 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_add_section_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_student_info',
            fields=[
                ('st_roll_no', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('st_name', models.CharField(max_length=50)),
                ('st_mob_no', models.CharField(max_length=25, unique=True)),
                ('st_email', models.CharField(max_length=50, unique=True)),
                ('st_year', models.IntegerField()),
                ('st_dob', models.DateField()),
                ('st_img', models.ImageField(default='', upload_to='static/ImgStaff/')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.add_section_info')),
            ],
        ),
    ]
