# Generated by Django 3.1.2 on 2020-12-03 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_add_student_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_student_info',
            old_name='course_name',
            new_name='branch_name',
        ),
    ]
