# Generated by Django 3.1.2 on 2020-12-03 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201203_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_student_info',
            name='course_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_student_info', to='user.add_section_info'),
        ),
    ]
