# Generated by Django 3.1.2 on 2020-12-03 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201203_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_student_info',
            name='branch_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='branch_names', to='user.add_section_info'),
        ),
    ]
