# Generated by Django 3.1.2 on 2020-12-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_add_student_info_branch_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_student_info',
            name='branch_name',
        ),
    ]
