# Generated by Django 3.1.2 on 2021-03-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_add_day_and_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='issued_book',
            fields=[
                ('book_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=30)),
            ],
        ),
    ]
