# Generated by Django 3.1.2 on 2021-03-02 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_issued_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issued_book',
            old_name='book_name',
            new_name='b_name',
        ),
        migrations.RenameField(
            model_name='issued_book',
            old_name='book_no',
            new_name='b_no',
        ),
    ]
