from . import views
from django.urls import path

urlpatterns = [
    path('', views.StaffLogin),
    path('StaffLogin/', views.StaffLogin),
    path('s_staff_panel/', views.s_staff_panel),
    path('s_log_in/', views.s_log_in),
    path('s_book_issue/', views.s_book_issue),
    path('s_book_issue_2/', views.s_book_issue_2),
    path('s_return_book/', views.s_return_book),
    path('s_return_book_2/', views.s_return_book_2),
    path('s_issued_book/', views.s_issued_book),
    path('s_search_book/', views.s_search_book),
    path('s_log_out/', views.s_log_out),
    path('AdminLogin/', views.AdminLogin),
    path('a_sign_in/', views.a_sign_in),
    path('a_admin_panel/', views.a_admin_panel),
    path('a_profile/', views.a_profile),
    path('a_change_password/', views.a_change_password),
    path('a_staff/', views.a_staff),
    path('a_add_staff/', views.a_add_staff),
    path('a_update_staff/', views.a_update_staff),
    path('a_student/', views.a_student),
    path('a_add_student/', views.a_add_student),
    path('a_update_student/', views.a_update_student),
    path('a_book/', views.a_book),
    path('a_add_book/', views.a_add_book),
    path('a_update_book/', views.a_update_book),
    path('a_course/', views.a_course),
    path('a_add_course/', views.a_add_course),
    path('a_update_course/', views.a_update_course),
    path('a_setting/', views.a_setting),
    path('a_add_day_fee/', views.a_add_day_fee),
    path('a_log_out/', views.a_log_out),
]